---
- name: Check if certificates exists | DNS-Route53
  stat:
    path: /etc/letsencrypt/live/{{ item }}/cert.pem
  register: _letsencrypt_certs
  with_items: "{{ certbot_domains }}"

- name: Generate new certificates if they do not exist | DNS-Route53
  command: >-
      {{ certbot_script }} certonly
      --dns-route53
      --dns-route53-propagation-seconds 30
      --noninteractive
      --agree-tos
      --email {{ certbot_email }}
      -d {{ item.item }}
  loop: "{{ _letsencrypt_certs.results }}"
  when: not item.stat.exists

- name: Create ssl.conf file per domain | DNS-Route53
  template:
    src: domain-ssl.conf.j2
    dest: "{{ apache_conf_path }}/vhost_{{ item }}-ssl.conf"
  with_items:
    - "{{ certbot_domains }}"
  notify: reload apache
