---
- name: install dependencies | Debian (before v.20.04)
  package:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - software-properties-common
  when: 
    - ansible_os_family == "Debian"
    - ansible_distribution_version is version('20.04', '<')
  

- name: Add certbot PPA | Debian (before v.20.04)
  apt_repository:
    repo: ppa:certbot/certbot
  when: 
    - ansible_os_family == "Debian"
    - ansible_distribution_version is version('20.04', '<')
  register: certbot_ppa_installed


- name: update apt cache | Debian (before v.20.04)
  apt: 
    update_cache: yes 
  when: 
    - ansible_os_family == "Debian" 
    - ansible_distribution_version is version('20.04', '<')
    - certbot_ppa_installed.changed
  

- name: install EPEL repository | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release

  when: ansible_os_family == "RedHat"  


- name: install certbot-apache | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-certbot-apache
  when: ansible_os_family == "RedHat"  
  
- name: install certbot-apache | Debian (before v20.04)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-certbot-apache
  when: 
    - ansible_os_family == "Debian" 
    - ansible_distribution_version is version('20.04', '<')

- name: install certbot-apache | Debian (v20.04+)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-certbot-apache
  when: 
    - ansible_os_family == "Debian" 
    - ansible_distribution_version is version('20.04', '>=')

    
- name: install Apache SSL module | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mod_ssl
  notify: reload apache
  when: ansible_os_family == "RedHat"  
  
      
- name: enable Apache SSL module | Debian
  command: >
    a2enmod ssl
    creates=/etc/apache2/mods-enabled/ssl.load
  notify: reload apache
  when: ansible_os_family == "Debian"
  
  
