---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: check for certbot_domain variable
  fail:
    msg: Parameters 'certbot_domain' must be provided.
  when: not certbot_domain

- name: check for certbot_email variable
  fail:
    msg: Parameters 'certbot_email' must be provided.
  when: not certbot_email
