---
- name: install Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dependencies }}"

# should there be a certbot user ????? probbaly
- name: Create Certbot directory
  file:
    path: "{{ certbot_dir }}"
    state: directory
    owner: "centos"
    group: "centos"
    mode: 0755

- name: Create and prepare python virtual environment for certbot
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ certbot_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ python_venv_command }}"
  with_items:
    - pip
    - wheel

# The items should be variable based on DNS provider
- name: Install certbot
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ certbot_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ python_venv_command }}"
  with_items:
    - certbot-apache
    - certbot-dns-route53
