---
- name: install package dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dependencies }}"

- name: Create the certbot group
  group:
    name: "{{ certbot_group }}"
    state: present
    system: true
  when:
    - certbot_group != "root"

- name: Create the certbot user
  user:
    name: "{{ certbot_user }}"
    groups: "{{ certbot_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when:
    - certbot_user != "root"

- name: Create Certbot directory
  file:
    path: "{{ certbot_dir }}"
    state: directory
    owner: "{{ certbot_user }}"
    group: "{{ certbot_group }}"
    mode: 0755

- name: Upgrade PIP and create python virtual environment for certbot
  pip:
    name: pip
    state: latest
    virtualenv: "{{ certbot_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ _python_path.stdout }} -m venv"

- name: Install ython dependencies
  pip:
    name: "{{ certbot_python_dependencies }}"
    state: latest
    virtualenv: "{{ certbot_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ _python_path.stdout }} -m venv"

# TODO The items should be variable based on DNS provider
- name: Install certbot and plugins
  pip:
    name:
      - certbot-apache
      - certbot-dns-route53
    state: present
    virtualenv: "{{ certbot_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ _python_path.stdout }} -m venv"
