---
- name: Create python virtual environment
  shell:
    cmd: "umask 0022 && {{ _python_path.stdout }} -m venv {{ certbot_bin_dir }}/{{ certbot_venv }}"
    creates: "{{ certbot_bin_dir }}/{{ certbot_venv }}"
  register: create_pyenv

- name: Upgrade PIP, wheel and setuptools    # noqa: no-handler
  shell:
    cmd: "umask 0022 && {{ certbot_bin_dir }}/{{ certbot_venv }}/bin/python -m pip install --upgrade pip setuptools wheel"
  changed_when: true
  when: create_pyenv.changed

- name: Install python dependencies
  pip:
    name: "{{ certbot_python_dependencies }}"
    state: present
    executable: "{{ certbot_bin_dir }}/{{ certbot_venv }}/bin/pip"
    umask: "0022"

- name: Install certbot and plugins
  pip:
    name:
      - certbot-apache
      - certbot-dns-route53
    state: present
    executable: "{{ certbot_bin_dir }}/{{ certbot_venv }}/bin/pip"
    umask: "0022"
