---
- name: Upgrade PIP and create python virtual environment for certbot
  pip:
    name: pip
    state: latest
    virtualenv: "{{ certbot_bin_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ _python_path.stdout }} -m venv"

- name: Install python dependencies
  pip:
    name: "{{ certbot_python_dependencies }}"
    state: present
    virtualenv: "{{ certbot_bin_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ _python_path.stdout }} -m venv"

- name: Install certbot and plugins
  pip:
    name:
      - certbot-apache
      - certbot-dns-route53
    state: present
    virtualenv: "{{ certbot_bin_dir }}/{{ certbot_venv }}"
    virtualenv_command: "{{ _python_path.stdout }} -m venv"

# When virtual environment is created, group `users` is set for all files/dirs
# group ownership of files created are determined by the group of the user who invoked sudo.
# setting ownership back to `certbot_user` and `certbot_group`
- name: Set ownership of virtual environment.
  file:
    path: "{{ certbot_bin_dir }}/{{ certbot_venv }}"
    state: directory
    owner: "{{ certbot_user }}"
    group: "{{ certbot_group }}"
    mode: 0755
    recurse: true
