---
- name: Load OS specific variables and execute varaible checks.
  import_tasks: preflight.yml

- name: Prepare host for certbot install.
  import_tasks: prepare.yml
  become: true

- name: Install Certbot.
  import_tasks: install-certbot.yml
  become: true

- name: Create well-known file for challenge
  import_tasks: well-known.yml
  become: true
  when: certbot_method == 'webroot'

# Multiple domains were provided
- name: Render domain list when multiple domains were provided
  set_fact:
    _certbot_all_domains: "{{ certbot_domains }}"
  when: certbot_domains is defined

# A single domain was provided
- name: Render Domain list when a single domain was provided
  set_fact:
    _certbot_all_domains:
      - "{{ certbot_domain }}"
  when: certbot_domains is not defined

- name: Create .well-known/acme-challenge directory for Certbot
  file:
    state: directory
    path: /var/www/html/.well-known/acme-challenge
    owner: "{{ certbot_user }}"
    group: "{{ certbot_group }}"
    mode: 0755
  become: true
  when: certbot_method == 'webroot'

- name: Create certificates with Webroot challenge
  import_tasks: create-cert-webroot.yml
  become: true
  become_user: "{{ certbot_user }}"
  when: certbot_method == 'webroot'

- name: Create certificates with DNS challenge via AWS Rt53
  import_tasks: create-cert-dns-route53.yml
  become: true
  become_user: "{{ certbot_user }}"
  when: certbot_method == 'dns-route53'

- name: Configure Apache.
  import_tasks: configure_apache.yml
  become: true
  when: certbot_configure_apache

- name: Schedule renewal via Cron.
  import_tasks: renew-cron.yml
  become: true
  when: certbot_auto_renew
