---
- import_tasks: preflight.yml

- import_tasks: prepare.yml
  become: true

- import_tasks: install-certbot.yml
  become: true
  become_user: "{{ certbot_user }}"

- import_tasks: well-known.yml
  become: true
  when: certbot_method == 'webroot'

- import_tasks: create-cert-webroot.yml
  become: true
  become_user: "{{ certbot_user }}"
  when: certbot_method == 'webroot'

- import_tasks: create-cert-dns-route53.yml
  become: true
  become_user: "{{ certbot_user }}"
  when: certbot_method == 'dns-route53'

- import_tasks: modify_apache.yml
  become: true

- import_tasks: renew-cron.yml
  become: true
  when: certbot_auto_renew
