---
- import_tasks: preflight.yml

# udpate apt_cache??

- import_tasks: install-certbot.yml
  become: true

# - import_tasks: dependencies.yml
#   become: yes

- import_tasks: well-known.yml
  become: yes

- import_tasks: create-cert.yml
  become: yes

- import_tasks: renew-cron.yml
  when: certbot_auto_renew
  become: yes
