---
- import_tasks: preflight.yml

- import_tasks: prepare.yml
  become: true

- import_tasks: install-certbot.yml
  become: true
  become_user: "{{ certbot_user }}"

- import_tasks: well-known.yml
  become: true
  when: certbot_method == 'webroot'

# Multiple domains were provided
- set_fact:
    _certbot_all_domains: "{{ certbot_domains }}"
  when: certbot_domains

# A single domain was provided
- set_fact:
    _certbot_all_domains: 
      - "{{ certbot_domain }}"
  when: certbot_domain

- import_tasks: create-cert-webroot.yml
  become: true
  become_user: "{{ certbot_user }}"
  when: certbot_method == 'webroot'

- import_tasks: create-cert-dns-route53.yml
  become: true
  become_user: "{{ certbot_user }}"
  when: certbot_method == 'dns-route53'

- import_tasks: modify_apache.yml
  become: true
  when: certbot_modify_apache

- import_tasks: renew-cron.yml
  become: true
  when: certbot_auto_renew
