---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Check for certbot_domains/certbot_domain variable (1).
  fail:
    msg: Either parameter 'certbot_domains' or 'certbot_domain' must be provided.
  when: 
    - not certbot_domains
    - not certbot_domain

- name: Check for certbot_domains/certbot_domain variable (2)
  fail:
    msg: Only one of 'certbot_domains' or 'certbot_domain' must be provided, not both
  when: 
    - certbot_domains
    - certbot_domain

- name: Check for certbot_email variable.
  fail:
    msg: Parameters 'certbot_email' must be provided.
  when: not certbot_email

- name: Find path for specified python version.
  command: "which {{ certbot_python }}"
  register: _python_path
  changed_when: false
