---
- name: Install package dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dependencies }}"

- name: Certbot is not root user
  when: certbot_group != "root"
  block:

    - name: Create the certbot group
      group:
        name: "{{ certbot_group }}"
        state: present
        system: true

    - name: Create the certbot user
      user:
        name: "{{ certbot_user }}"
        groups: "{{ certbot_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /

    - name: Give permission for certbot user to reload apache
      template:
        src: sudoers.j2
        dest: "/etc/sudoers.d/{{ certbot_user }}"
        mode: 0644
      when: certbot_method == 'webroot'

- name: Create Certbot directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ certbot_user }}"
    group: "{{ certbot_group }}"
    mode: 0755
  with_items:
    - "{{ cerbot_work_dir }}"
    - "{{ certbot_log_dir }}"
    - "{{ certbot_config_dir }}"
    - "{{ certbot_bin_dir }}"
