---
- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
    special_time: daily
    user: "{{ certbot_auto_renew_user }}"
    cron_file: ansible_certbot_renew
  notify: Reload cron
