---
# ---------------------------------------------
# Figure out what version of Apache is installed.
# ---------------------------------------------
- name: Get installed version of Apache.
  shell: "{{ apache_daemon_path }}{{ apache_daemon }} -v"
  changed_when: false
  check_mode: no
  register: _apache_version

## This will create full version, like 2.4.6
- set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

## Translate full apache_version (2.4.5) to the MAJOR.MINOR value, like "2.4"
- set_fact:
    apache_version_base: "{{ '.'.join(apache_version.split('.')[:2]) }}"

# --------------------------------------------------
# Apache conf.d/letsencrypt-well-known.conf
# --------------------------------------------------
- name: Install letsencrypt-well-known.conf
  template:
    src: "apache-{{ apache_version_base }}-letsencrypt-well-known.conf.j2"
    dest: "{{ apache_conf_path }}/letsencrypt-well-known.conf"
  notify: reload apache
  register: _letsencrypt_well_known

- name: reload apache configuration
  service:
    name: "{{ apache_service }}"
    state: reloaded
  when: _letsencrypt_well_known.changed
  become: yes
