---
- name: reload apache
  service:
    name: "{{ apache_service }}"
    state: reloaded
  become: true

- name: reload cron
  service:
    name: "{{ cron_service }}"
    state: restarted
  become: true
