---
- name: Converge
  hosts: all
  become: true
  vars:
    certbot_domain: ansible-role-letsencrypt.example.com
    certbot_email: ssl-molecule@example.com
    certbot_method: none
    certbot_configure_apache: false

  pre_tasks:
    - set_fact:
        ansible_python_interpreter: python3
      when: ansible_distribution == "CentOS"

  roles:
    - role: ansible-role-letsencrypt
      tags:
        - letsencrypt
