---
- name: CentOS 7 - Install Python3.8 from package - RPM
  block:

    - name: CentOS 7 - Install Python3.8 dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - centos-release-scl-rh

    - name: CentOS 7 - Install Python3.8 packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - rh-python38-python
        - rh-python38-python-devel

    - name: Create Symbolic link
      file:
        src: /opt/rh/rh-python38/root/usr/bin/python3.8
        dest: /usr/bin/python3
        state: link

  when: ansible_distribution == "CentOS"