---
- name: Install Python3.8 | CentOS
  when: ansible_distribution == "CentOS"
  block:
    - name: Prepare | Install Python3.8 dependencies | CentOS
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - centos-release-scl-rh

    - name: Prepare | Install Python3.8 packages | CentOS
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - rh-python38-python
        - rh-python38-python-devel

    - name: Prepare | Create Symbolic link | CentOS
      file:
        src: /opt/rh/rh-python38/root/usr/bin/python3.8
        dest: /usr/bin/python3
        state: link

- name: Install Python3.8 or later | Rocky
  when: ansible_distribution == "Rocky"
  block:

    - set_fact:
        _python_packages:
          - python38
          - python38-devel
      when: ansible_distribution_major_version == "8"

    - set_fact:
        _python_packages:
          - python3
          - python3-devel
      when: ansible_distribution_major_version == "9"

    # - debug: var=_python_packages

    - name: Install Python 3.8 or later | Rocky
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ _python_packages }}"
