---
- name: Install Python3 Dependencies
  package:
    name: epel-release
    state: present
  # with_items:
  #   - epel-release
  # when: ansible_os_family == "RedHat"

# Install python from package
- name: Install Python3 packages
  package:
    name: python3
    state: present
  # with_items: "{{ python3_packages }}"