---
- name: Prepare | Python3 | Install Python3.8 dependencies | CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl-rh

- name: Prepare | Python3 | Install Python3.8 packages | CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - rh-python38-python
    - rh-python38-python-devel

- name: Prepare | Python3 | Create Symbolic link | CentOS
  file:
    src: /opt/rh/rh-python38/root/usr/bin/python3.8
    dest: /usr/bin/python3
    state: link
