---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: false
          yamllint_config_filepath: '.yamllint'
